CREATE TABLE REQ_SBERPAY_CONNECT
(
    entity_id                       VARCHAR2(32 CHAR) NOT NULL,
    req_num                         VARCHAR2(50 CHAR),
    req_status                      VARCHAR2(50 CHAR),
    req_created_date                TIMESTAMP(6)        NOT NULL,
    req_created_date_part           TIMESTAMP(6)        NOT NULL,
    req_resolved_date               TIMESTAMP(6),
    req_updated_date                TIMESTAMP(6),
    req_user                        VARCHAR2(50 CHAR),
    req_departure                   VARCHAR2(50 CHAR),
    req_client_id                   VARCHAR2(50 CHAR),
    req_product                     VARCHAR2(50 CHAR),
    req_counterparty_id             VARCHAR2(50 CHAR),
    req_counterparty_type           VARCHAR2(50 CHAR),
    req_agreement_id                VARCHAR2(50 CHAR),
    req_mdm_id                      VARCHAR2(50 CHAR),
    req_erib_id                     VARCHAR2(20 CHAR),
    req_back_office_entity_id       VARCHAR2(80 CHAR),
    req_charge_res_id               NUMBER(19),
    req_charge_res_name             VARCHAR2(50 CHAR),
    req_charge_res_number           VARCHAR2(50 CHAR),
    req_charge_res_type             VARCHAR2(50 CHAR),
    req_receiver_res_id             NUMBER(19),
    req_receiver_res_name           VARCHAR2(50 CHAR),
    req_receiver_res_number         VARCHAR2(50 CHAR),
    req_receiver_res_type           VARCHAR2(50 CHAR),
    req_receiver_name               VARCHAR2(50 CHAR),
    req_doc_type                    VARCHAR2(50 CHAR),
    req_status_description          VARCHAR2(256 CHAR),
    req_system_status               VARCHAR2(50 CHAR),
    req_doc_amount                  NUMBER(19, 2),
    req_charge_amount_cur_code      VARCHAR2(50 CHAR),
    req_receiver_amount_cur_code    VARCHAR2(50 CHAR),
    req_op_descr                    VARCHAR2(512 CHAR),
    entity_deleted                  CHAR(1) DEFAULT 'N' NOT NULL,
    req_bankinfo_rb_tb_brch_id      VARCHAR2(50 CHAR),
    req_channel                     VARCHAR2(50 CHAR),
    req_comments                    VARCHAR2(200 CHAR),
    req_comment_to_block            VARCHAR2(200 CHAR),
    req_block_client                VARCHAR2(20 CHAR),
    req_confirm_type                VARCHAR2(20 CHAR),
    req_is_visible                  CHAR(1)             NOT NULL,
    req_version                     NUMBER(19) NOT NULL,
    req_client_transaction_id       VARCHAR2(255 CHAR),
    custom_field                    VARCHAR2(100 CHAR),
    greg_calendar                   TIMESTAMP(6),
    req_operation_uid               VARCHAR2(36) NOT NULL,
    req_modified_date               TIMESTAMP(6),
    req_modified_block              VARCHAR2(20 CHAR),
    REQ_ID_V6                       VARCHAR2(36 CHAR),
    REQ_OPERATION_UUID_V6           VARCHAR2(36 CHAR),
    REQ_AMOUNT_CUR_CODE_V6          VARCHAR2(50 CHAR),
    REQ_ORIGIN_BLOCK_ID_UFS         VARCHAR2(4 CHAR),
    REQ_ORIGIN_ERIB_ID              VARCHAR2(20 CHAR),
    ENTITY_DATA                     CLOB,
    REQ_ACCOUNTING_TRANSACTION_TYPE VARCHAR2(7 CHAR),
    REQ_CURRENCY                    VARCHAR2(3 CHAR),
    REQ_NATIONAL_SUMM               NUMBER(19, 4),
    REQ_MCC_CODE                    NUMBER(10),
    REQ_COMMISSION                  NUMBER(15, 4),
    REQ_COMMISSION_CUR              CHAR(3 CHAR) ,
    REQ_ADDITIONAL_ID               VARCHAR2(100),
    REQ_CHARGE_RES_AMOUNT           NUMBER(19, 4),
    REQ_RECEIVER_RES_AMOUNT         NUMBER(19, 4),
    REQ_ADDITIONAL_ATTR             VARCHAR2(6 CHAR) DEFAULT NULL,
    REQ_BACK_OFFICE_SYSTEM          VARCHAR2(15 CHAR),
    REQ_SUDIR_ID                    VARCHAR2(50 CHAR),
    REQ_EMPLOYEE_INFO_ID            VARCHAR2(32 CHAR),

    CLIENT_NAME                     VARCHAR2(255),
    OPERATION_DATE                  TIMESTAMP(6),
    EXECUTION_DATE                  TIMESTAMP(6),
    DOCUMENT_DATE                   TIMESTAMP(6),
    SESSION_ID                      VARCHAR2(255)                NOT NULL,
    TERMINAL_ID                     VARCHAR2(255)                NOT NULL,
    ORDER_NUMBER                    VARCHAR2(255),
    RRN                             VARCHAR2(15),
    AUTHORIZATION_CODE              VARCHAR2(32),
    SV_NODE_ID                      VARCHAR2(32),
    ORDER_LIFE_TIME                 NUMBER(10),
    ORDER_CREATION_DATE_TIME        TIMESTAMP(6),
    CARD_TITLE                      VARCHAR2(255),
    CARD_TYPE                       VARCHAR2(20),
    PAY_SYSTEM_TYPE                 CHAR(1),
    CARD_BALANCE                    NUMBER(19, 4),
    MERCHANT_NAME                   VARCHAR2(160),
    PAYMENT_SCENARIO                VARCHAR2(30)  DEFAULT 'OneStagePayment' NOT NULL,
    IS_RECURRING_PAYMENT            CHAR(1)  DEFAULT 'N' NOT NULL,
    TEXT_FOR_CLIENT                 VARCHAR2(4000),
    BINDING_IS_NEEDED               CHAR(1) DEFAULT 'N' NOT NULL,
    RECALLED_DATE                   TIMESTAMP(6),
    RECALLED_ID                     VARCHAR2(32)
);

ALTER TABLE REQ_SBERPAY_CONNECT
    ADD MOBILE_PHONE_NUMBER VARCHAR2(16);

ALTER TABLE REQ_SBERPAY_CONNECT
    ADD CARD_NUMBER VARCHAR2(50 CHAR);
